apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ui
spec:
  replicas: 1
  template:
    metadata:
      name: ui
      labels:
        app: sk8s
        component: ui
    spec:
      containers:
      - image: jldec/sk8s-ui:latest
        name: ui
        imagePullPolicy: IfNotPresent
        env:
        - name: REDIS_HOST
          value: "counters-redis.default.svc.cluster.local"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: counters-redis
              key: redis-password
      - image: sk8s/function-sidecar:0.0.1-SNAPSHOT
        name: sidecar
        imagePullPolicy: IfNotPresent
        env:
        - name: SPRING_APPLICATION_JSON
          value: '{"spring.cloud.stream.bindings.input.destination":"function-replicas","spring.cloud.stream.bindings.output.destination":"replies","spring.cloud.stream.bindings.input.group":"ui","spring.profiles.active":"http","spring.application.name":"sidecar-ui","spring.cloud.stream.kafka.binder.brokers":"kafka:9092","spring.cloud.stream.kafka.binder.zkNodes":"zookeeper:2181","server.port":"-1"}'
      serviceAccountName: sk8s-sa
