#!/bin/bash

## prereqs: redis-cli and redis installed via helm with name "counters" and NodePort serviceType

export REDIS_PORT=$(kubectl get svc counters-redis -o jsonpath='{.spec.ports[0].nodePort}')
export REDIS_HOST=$(minikube ip)
export REDIS_PASSWORD=$(kubectl get secret --namespace default counters-redis -o jsonpath="{.data.redis-password}" | base64 --decode)

redis-cli -h $REDIS_HOST \
          -p $REDIS_PORT \
          -a $REDIS_PASSWORD
