#!/bin/bash

kubectl delete function vote-stream-processor
sleep 5
kubectl delete function redis-writer
sleep 5
kubectl delete function vote-counter

#kubectl delete topic votes
#kubectl delete topic counted-votes
#kubectl delete topic function-replicas

