kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: votes-ui
  labels:
    app: votes
    component: ui
rules:
  - apiGroups: [""]
    resources: ["services", "pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["extensions"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["projectriff.io"]
    resources: ["functions", "topics"]
    verbs: ["get", "list", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: votes-ui
  labels:
    app: votes
    component: ui
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: votes-ui
  labels:
    app: votes
    component: ui
roleRef:
  kind: Role
  name: votes-ui
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: votes-ui
