apiVersion: v1
kind: Service
metadata:
  name: votes-ui
  labels:
    app: votes
    component: ui
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http
    targetPort: 8080
  selector:
    app: votes
    component: ui
