= redis-writer

[horizontal]
*Language*:: Java
*Function*:: https://github.com/markfisher/s1p2017-faas-demo/blob/master/functions/redis-writer/src/main/java/functions/RedisWriter.java[RedisWriter.java]
*Protocol*:: HTTP
*Input*:: votes

=== Build the Docker container for the function code

ensure riff is running and the `riff` script from `project/riff` is on your `PATH`

from within the `functions/redis-writer` directory execute:

```
./mvnw clean package
eval $(minikube docker-env)
riff build -v 1.0.0
riff apply
```

to run a function that subscribes to the `votes` topic and produces aggregates
for every 2 second interval into a `vote-interval-counts` topic, change to the
`vote-interval-counter` sibling directory and execute:

```
./mvnw clean package
riff build -v 1.0.0
riff apply
```

then (back in this dir) add a `redis-writer` that subscribes to that
`vote-interval-counts` topic and writes each entry into "demo:votes-log" list:

```
riff apply -f vote-interval-writer/
```

if you'd also like to run an instance of `redis-writer` that subscribes to the
`function-replicas` topic and keeps track of the latest values in a
"demo:function-replicas" hash:

```
riff apply -f function-replicas-writer
```
