apiVersion: projectriff.io/v1
kind: Topic
metadata:
  name: function-replicas
---

apiVersion: projectriff.io/v1
kind: Function
metadata:
  name: redis-writer
spec:
  protocol: http
  input: function-replicas
  idleTimeoutMs: 60000
  container:
    image: projectriff/redis-writer:0.0.2
    env:
    - name: DEFAULT_HASH_KEY
      value: demo:function-replicas
    - name: REDIS_PASSWORD
      valueFrom:
        secretKeyRef:
          name: counters-redis
          key: redis-password
