apiVersion: extensions.sk8s.io/v1
kind: Topic
metadata:
  name: function-replicas
---

apiVersion: extensions.sk8s.io/v1
kind: Function
metadata:
  name: redis-writer
spec:
  protocol: http
  input: function-replicas
  container:
    image: sk8s/redis-writer:1.0.0
    env:
    - name: FUNCTION_URI
      value: file:///functions/function.jar?functions.RedisWriter
    - name: REDIS_PASSWORD
      valueFrom:
        secretKeyRef:
          name: counters-redis
          key: redis-password
