apiVersion: v1
kind: Service
metadata:
  name: ui
  labels:
    app: riff
    component: ui
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
    targetPort: 8080
  selector:
    component: ui
